### ISSUE TITLE
Ractive events on `<btn` element doesn't work

### ISSUE THREAD

**Issue by ceremcem** [dagnelies/ractive-bootstrap#1]
`<btn on-click="myRactiveEvent"` doesn't fire `myRactiveEvent` that is registered by `ractive.on({myRactiveEvent: function....`. 

Here is the fiddle: https://jsfiddle.net/un2Lsrxb/2/

**Comment by ceremcem** [comment]
It turns out that there might be an issue with ractive itself: https://github.com/ractivejs/ractive/issues/2586

**Comment by dagnelies** [comment]
In ractive latest, components cannot handle events, as seen in:
https://github.com/ractivejs/ractive/issues/1684
...I'll also wait until edge stabilizes until I do something about it.

Note that you can use direct events though:

```
<btn onclick="alert('hey!')">Ho</btn>
```

**Comment by ceremcem** [comment]
These ractive-bootstrap components are heavily used inside our own components, so they have to trigger functions which are defined as component's private function. Is there any workaround for this?

**Comment by dagnelies** [comment]
Dunno. When I developed this, ractive had no support for component events at all.
I think it's worked on in edge, but I don't know the details.
