### ISSUE TITLE
modal fade needs to be configurable

### ISSUE THREAD

**Issue by lazylester** [dagnelies/ractive-bootstrap#3]
Documenting this here in case others run into the same issue, which has recently surfaced in a test suite that has long been reliable:

My test suites have recently become unreliable. Seems to be due to some speed changes in js, perhaps in recent chrome browser, not exactly sure. The symptom is that the fade feature of bootstrap modals is "clobbering" text that is entered into a form within a modal. This is prevented by disabling the fade class, but in ractive-bootstrap it's hard-coded.

Therefore I have found it necessary to dynamically disable fade (i.e. remove the fade class) from modals in my test suite, I'm using the Ractive 'class-' directive.

so my modal component template now starts like this:
`<div class='modal' class-fade='fade' ... etc`

where 'fade' is a computed boolean attribute which is false for testing and true otherwise.

**Comment by dagnelies** [comment]
Hi,

thanks for the information. I left it open for a while so that people can see it and if maybe others were annoyed by this too. However, since it's quite specific and this fade seems OK as a default, I'll leave it like this. If some other complains come, I'll make an attribute flag for it.
